// The Teach panel: points, frames and work objects — the teaching loop as
// this gateway actually supports it, with its limits stated rather than
// papered over.
//
// What IS possible on this firmware (v3.8.5.1-class):
//   * capture the live pose (joints + TCP from the telemetry stream) into a
//     point store kept BY THE CONSOLE (localStorage),
//   * generate a program from captured points using literal-pose MoveJ/MoveL
//     (prototypes from the vendor manual, arity-verified on this firmware) —
//     literal poses are what keep the gateway's path pre-flight working,
//   * read a named point from the controller's own teaching database
//     (GetRobotTeachingPoint, hardware-verified; error 143 = no such point),
//   * move whole point tables: download / restore (readback-verified) /
//     switch,
//   * define tool frames (1-15) and work object frames (0-14).
//
// What is NOT possible, per the gateway's own evidence: writing a single
// named point into the controller's database (no RPC exists; the Lua
// SetPointToDatabase is a confirmed silent no-op), listing tables or points,
// deleting a table. The panel never pretends otherwise.

import { ApiError } from './api.js';
import { confirmGateway, dialog, skeleton } from './ui.js';

const esc = (s) => String(s ?? '').replace(/[&<>"]/g,
  (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

const LS_POINTS = 'fws-teach-points';
const LS_TABLES = 'fws-seen-point-tables';

const loadPoints = () => {
  try { return JSON.parse(localStorage.getItem(LS_POINTS)) || []; }
  catch { return []; }
};
const savePoints = (pts) => localStorage.setItem(LS_POINTS, JSON.stringify(pts));

const fmt = (v, d = 2) => (typeof v === 'number' ? v.toFixed(d) : '—');

// Literal-pose move lines. Prototypes from the controller's own manual
// catalogue (GET /api/v1/lua/functions/MoveJ|MoveL), arity accepted by this
// firmware. Conservative defaults; the header comment in the generated
// program tells the developer what to review.
function moveJ(p, speed) {
  const j = p.joints.map((v) => v.toFixed(3)).join(', ');
  const c = p.tcp.map((v) => v.toFixed(3)).join(', ');
  return `MoveJ(${j}, ${c}, ${p.tool ?? 0}, ${p.wobj ?? 0}, ${speed}, 100, 100, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0)`;
}
function moveL(p, speed) {
  const j = p.joints.map((v) => v.toFixed(3)).join(', ');
  const c = p.tcp.map((v) => v.toFixed(3)).join(', ');
  return `MoveL(${j}, ${c}, ${p.tool ?? 0}, ${p.wobj ?? 0}, ${speed}, 100, 100, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0)`;
}

function generateProgram(points, speed) {
  const lines = [
    '-- generated by FWS Console Teach from captured poses.',
    '-- Literal-pose MoveJ: the gateway pre-flights every target against',
    '-- soft limits before run. Review speed/acc (percent) before running.',
    '',
  ];
  for (const p of points) {
    lines.push(`-- ${p.name}  (taught ${new Date(p.at).toLocaleString()})`);
    lines.push(moveJ(p, speed));
  }
  return lines.join('\n') + '\n';
}

export async function teach(root, api, log, toast) {
  root.innerHTML = `
    <div class="grid cols-3">
      <div class="card" style="grid-column:span 2">
        <h2>Taught points
          <span class="spacer"></span>
          <span class="small faint">stored by this console — the controller
            has no per-point write</span></h2>
        <div class="field-row" style="margin-top:0">
          <input id="tp-name" placeholder="point name" style="width:160px" class="mono">
          <button class="btn btn-primary btn-sm" id="tp-capture">Capture pose</button>
          <span class="small dim" id="tp-live">waiting for telemetry…</span>
        </div>
        <div class="scroll" style="max-height:300px;margin-top:10px"><table>
          <thead><tr><th style="text-align:left">Name</th>
          <th style="text-align:left">Joints °</th>
          <th style="text-align:left">TCP mm·°</th><th></th></tr></thead>
          <tbody id="tp-rows"></tbody></table></div>
        <div class="field-row" style="margin-top:10px">
          <label>speed %</label>
          <input id="tp-speed" type="number" value="25" min="1" max="100" style="width:70px">
          <button class="btn btn-sm btn-primary" id="tp-sim">Sim run</button>
          <button class="btn btn-sm" id="tp-gen">Generate program</button>
          <span class="small faint">Sim run animates a ghost through the
            points in the 3D view — the robot does not move</span>
        </div>
      </div>

      <div class="card">
        <h2>Controller point lookup</h2>
        <div class="field-row" style="margin-top:0">
          <input id="cp-name" placeholder="name on the pendant" class="mono" style="flex:1">
          <button class="btn btn-sm" id="cp-read">Read</button>
        </div>
        <div id="cp-out" class="small" style="margin-top:8px"></div>
        <div class="small faint" style="margin-top:8px">
          Reads the controller's own teaching database
          (<span class="mono">GetRobotTeachingPoint</span>, verified on this
          hardware). There is no list call — only names you know.</div>
      </div>

      <div class="card">
        <h2>Tool frame</h2>
        <div id="tf-now" class="small dim">${skeleton(2)}</div>
        <div class="field-row" style="margin-top:10px">
          <label>id</label>
          <input id="tf-id" type="number" value="1" min="1" max="15" style="width:60px">
        </div>
        <div class="teach-vec" id="tf-vec"></div>
        <button class="btn btn-sm" id="tf-set" data-cmd="1" style="margin-top:8px">
          Define tool frame</button>
        <div class="small faint" style="margin-top:8px">
          Offset of the tool point from the FLANGE, mm and degrees. Tool ids
          are 1–15; work objects 0–14 — the ranges differ.</div>
      </div>

      <div class="card">
        <h2>Work object frame</h2>
        <div id="wf-now" class="small dim">${skeleton(2)}</div>
        <div class="field-row" style="margin-top:10px">
          <label>id</label>
          <input id="wf-id" type="number" value="0" min="0" max="14" style="width:60px">
          <label>ref</label>
          <input id="wf-ref" type="number" value="0" min="0" max="14" style="width:60px">
          <button class="btn btn-sm btn-ghost" id="wf-fill">use current TCP</button>
        </div>
        <div class="teach-vec" id="wf-vec"></div>
        <button class="btn btn-sm" id="wf-set" data-cmd="1" style="margin-top:8px">
          Define work object</button>
        <button class="btn btn-sm btn-ghost" id="wf-reset" data-cmd="1"
                style="margin-top:8px">Reset to base</button>
        <div class="small faint" style="margin-top:8px">
          Teach a workpiece origin: jog the TCP to it, "use current TCP",
          define. Every position expressed in this frame moves with it.
          Reset makes the frame coincide with base again (all zeros, ref 0).</div>
      </div>

      <div class="card">
        <h2>Point tables <span class="small faint">(whole .db files)</span></h2>
        <div class="field-row" style="margin-top:0">
          <input id="pt-name" placeholder="table.db" class="mono" style="flex:1">
          <button class="btn btn-sm" id="pt-dl">Download</button>
          <button class="btn btn-sm" id="pt-switch" data-cmd="1">Switch to</button>
        </div>
        <div class="field-row">
          <label class="btn btn-sm">Restore…
            <input type="file" id="pt-file" accept=".db" class="sr-only" data-cmd="1">
          </label>
          <button class="btn btn-sm btn-ghost" id="pt-off" data-cmd="1"
                  title="Deactivate the active table">deactivate</button>
        </div>
        <div id="pt-out" class="small" style="margin-top:8px"></div>
        <div class="small faint" style="margin-top:8px">
          Tables move whole — there is no list, no delete, no per-point edit.
          A 404 means the controller declined (probably absent); a 502 means
          the table EXISTS but the copy failed — never restore over that.
          Restore is unverified on real hardware; the readback verdict is
          shown after every restore.</div>
        <div class="small dim" id="pt-seen" style="margin-top:6px"></div>
      </div>

      <div class="card">
        <h2>Drag teach <span class="tag warn">experimental</span></h2>
        <div class="field-row" style="margin-top:0">
          <button class="btn btn-sm" id="dt-on" data-cmd="1">Enter drag teach</button>
          <button class="btn btn-sm" id="dt-off" data-cmd="1">Exit</button>
          <span id="dt-state" class="small dim">state unknown</span>
        </div>
        <div class="banner warn" style="margin-top:10px">
          <svg viewBox="0 0 17 17"><use href="#i-fault"/></svg>
          <span class="small">Hand-guide mode: the arm goes compliant and can
          be moved by hand, then poses captured above. This command is NOT
          verified on this hardware — the true state is polled below; trust
          it, not the button you pressed.</span>
        </div>
      </div>
    </div>`;

  const $id = (s) => root.querySelector(s);

  // --- live pose from the telemetry stream --------------------------------
  let live = null;          // {joints:[6], tcp:[6]}
  let activeTool = 0, activeWobj = 0;
  const liveEl = $id('#tp-live');
  const onFrame = (ev) => {
    if (root.closest('section')?.hidden) return;
    const f = ev.detail;
    if (f.joints && f.tcp) {
      live = { joints: f.joints.slice(0, 6), tcp: f.tcp.slice(0, 6) };
      liveEl.textContent =
        `J ${live.joints.map((v) => v.toFixed(1)).join(' ')}  ·  `
        + `TCP ${live.tcp.slice(0, 3).map((v) => v.toFixed(1)).join(' ')}`;
    }
  };
  document.addEventListener('fws-frame', onFrame);
  api.get('/api/v1/robot/frames/active').then((r) => {
    activeTool = r.tool ?? 0;
    activeWobj = r.work ?? r.wobj ?? 0;
  }).catch(() => { /* capability-gated; defaults stand */ });

  // --- taught points ------------------------------------------------------
  const renderPoints = () => {
    const pts = loadPoints();
    $id('#tp-rows').innerHTML = pts.map((p, i) => `
      <tr><td style="text-align:left" class="mono">${esc(p.name)}</td>
      <td style="text-align:left" class="mono small dim">${p.joints.map((v) => v.toFixed(1)).join(' ')}</td>
      <td style="text-align:left" class="mono small dim">${p.tcp.map((v) => v.toFixed(1)).join(' ')}</td>
      <td style="text-align:right;white-space:nowrap">
        <button class="btn btn-sm btn-ghost" data-lua="${i}">lua</button>
        <button class="btn btn-sm btn-ghost" data-del="${i}">delete</button>
      </td></tr>`).join('')
      || '<tr><td colspan="4"><span class="small faint">no points yet — jog the arm, name the pose, capture</span></td></tr>';

    for (const b of root.querySelectorAll('[data-del]')) {
      b.onclick = () => {
        const pts2 = loadPoints();
        pts2.splice(Number(b.dataset.del), 1);
        savePoints(pts2);
        renderPoints();
      };
    }
    for (const b of root.querySelectorAll('[data-lua]')) {
      b.onclick = async () => {
        const p = loadPoints()[Number(b.dataset.lua)];
        if (!p) return;
        const speed = Number($id('#tp-speed').value) || 25;
        await dialog({
          title: `${p.name} as Lua`,
          body: `<pre class="jsonview" style="user-select:all">${esc(
            `-- joint-space:\n${moveJ(p, speed)}\n-- straight-line:\n${moveL(p, speed)}`)}</pre>
            <p class="small faint">Select and copy. Literal poses keep the
            gateway's path pre-flight working.</p>`,
          confirmLabel: 'Close',
        });
      };
    }
  };
  renderPoints();

  $id('#tp-capture').onclick = () => {
    if (!live) { toast('no telemetry yet', 'warn'); return; }
    const name = ($id('#tp-name').value.trim() || `P${loadPoints().length + 1}`)
      .replace(/[^\w.-]/g, '_');
    const pts = loadPoints();
    pts.push({ name, joints: live.joints, tcp: live.tcp,
               tool: activeTool, wobj: activeWobj, at: Date.now() });
    savePoints(pts);
    $id('#tp-name').value = '';
    log(`taught ${name}`, 'ok');
    renderPoints();
  };

  $id('#tp-sim').onclick = () => {
    const pts = loadPoints();
    if (!pts.length) { toast('capture at least one point first', 'warn'); return; }
    document.dispatchEvent(new CustomEvent('fws-sim-run', {
      detail: {
        waypoints: pts.map((p) => p.joints),
        speed: Number($id('#tp-speed').value) || 25,
      },
    }));
  };

  $id('#tp-gen').onclick = async () => {
    const pts = loadPoints();
    if (!pts.length) { toast('capture at least one point first', 'warn'); return; }
    const speed = Math.min(100, Math.max(1, Number($id('#tp-speed').value) || 25));
    await dialog({
      title: `Program from ${pts.length} point${pts.length > 1 ? 's' : ''}`,
      body: `<pre class="jsonview" style="user-select:all;max-height:300px">${esc(generateProgram(pts, speed))}</pre>
        <p class="small faint">Select, copy, paste into Develop, save — the
        gateway validates and pre-flights it before any run.</p>`,
      confirmLabel: 'Close',
    });
  };

  // --- controller point lookup -------------------------------------------
  $id('#cp-read').onclick = async () => {
    const name = $id('#cp-name').value.trim();
    const out = $id('#cp-out');
    if (!name) return;
    out.innerHTML = '<span class="small dim">asking the controller…</span>';
    try {
      const r = await api.post(
        `/api/v1/invoke/${encodeURIComponent('GetRobotTeachingPoint')}`,
        { args: [name] });
      out.innerHTML = `<pre class="jsonview">${esc(JSON.stringify(r, null, 2))}</pre>`;
    } catch (e) {
      const is143 = /\b143\b/.test(e.message || '');
      out.innerHTML = `<span class="tag ${is143 ? '' : 'bad'}">${
        is143 ? 'no such point' : 'failed'}</span> <span class="small dim">${esc(e.message)}</span>`;
    }
  };

  // --- frames -------------------------------------------------------------
  const vecInputs = (host, labels) => {
    host.innerHTML = labels.map((l) =>
      `<label class="small dim">${l}<input data-vec="${l}" type="number"
        step="0.01" value="0" class="mono"></label>`).join('');
  };
  vecInputs($id('#tf-vec'), ['x', 'y', 'z', 'rx', 'ry', 'rz']);
  vecInputs($id('#wf-vec'), ['x', 'y', 'z', 'rx', 'ry', 'rz']);
  const readVec = (host) =>
    [...host.querySelectorAll('[data-vec]')].map((i) => parseFloat(i.value) || 0);

  const showFrames = async () => {
    try {
      const t = await api.get('/api/v1/frames/tool');
      $id('#tf-now').innerHTML =
        `active <b>${t.active}</b>${t.offset ? ` · offset <span class="mono">${
          t.offset.slice(1, 7).map((v) => fmt(v, 1)).join(', ')}</span>` : ''}`;
    } catch (e) { $id('#tf-now').textContent = e.message; }
    try {
      const w = await api.get('/api/v1/frames/work');
      $id('#wf-now').innerHTML =
        `active <b>${w.active}</b>${w.offset ? ` · offset <span class="mono">${
          w.offset.slice(1, 7).map((v) => fmt(v, 1)).join(', ')}</span>` : ''}`;
    } catch (e) { $id('#wf-now').textContent = e.message; }
  };
  showFrames();

  const putFrame = async (path, body, label,
                          dialog = { title: 'Define this frame?',
                                     confirmLabel: 'Define it' }) => {
    try {
      await api.put(path, body);
      log(label, 'ok');
      showFrames();
    } catch (e) {
      // The gateway refuses once without confirm, stating the consequence in
      // its own words; surface that text, then resend confirmed.
      if (e instanceof ApiError && e.status === 400
          && await confirmGateway(e.message, dialog)) {
        try {
          await api.put(path, { ...body, confirm: true });
          log(`${label} (confirmed)`, 'ok');
          showFrames();
          return;
        } catch (e2) { log(`${label}: ${e2.message}`, 'err'); toast(e2.message, 'err'); return; }
      }
      log(`${label}: ${e.message}`, 'err');
      toast(e.message, 'err');
    }
  };

  $id('#tf-set').onclick = () => {
    const id = Number($id('#tf-id').value);
    putFrame(`/api/v1/frames/tool/${id}`,
      { offset: readVec($id('#tf-vec')) }, `tool frame ${id} defined`);
  };
  $id('#wf-fill').onclick = () => {
    if (!live) { toast('no telemetry yet', 'warn'); return; }
    [...$id('#wf-vec').querySelectorAll('[data-vec]')].forEach((inp, i) => {
      inp.value = live.tcp[i].toFixed(2);
    });
  };
  $id('#wf-set').onclick = () => {
    const id = Number($id('#wf-id').value);
    putFrame(`/api/v1/frames/work/${id}`,
      { offset: readVec($id('#wf-vec')), ref_frame: Number($id('#wf-ref').value) },
      `work object ${id} defined`);
  };
  $id('#wf-reset').onclick = () => {
    // Reset = an ordinary define with the identity frame. Deliberately not a
    // separate gateway call: the wire has no "unset", only SetWObjCoord, and
    // pretending otherwise would hide what is actually sent.
    const id = Number($id('#wf-id').value);
    putFrame(`/api/v1/frames/work/${id}`,
      { offset: [0, 0, 0, 0, 0, 0], ref_frame: 0 },
      `work object ${id} reset to base`,
      { title: 'Reset this work object?', confirmLabel: 'Reset it' });
  };

  // --- point tables -------------------------------------------------------
  const seen = () => {
    try { return JSON.parse(localStorage.getItem(LS_TABLES)) || []; }
    catch { return []; }
  };
  const remember = (n) => {
    const s = seen();
    if (!s.includes(n)) { s.push(n); localStorage.setItem(LS_TABLES, JSON.stringify(s)); }
    renderSeen();
  };
  const renderSeen = () => {
    $id('#pt-seen').textContent =
      seen().length ? `seen here: ${seen().join(', ')}` : '';
  };
  renderSeen();

  const ptOut = $id('#pt-out');
  const tableName = () => {
    let n = $id('#pt-name').value.trim();
    if (n && !n.endsWith('.db')) n += '.db';
    return n;
  };

  $id('#pt-dl').onclick = async () => {
    const n = tableName();
    if (!n) return;
    ptOut.innerHTML = '<span class="small dim">downloading…</span>';
    try {
      const r = await api.get(`/api/v1/points/tables/${encodeURIComponent(n)}`,
        { timeout: 60000 });
      const bytes = Uint8Array.from(atob(r.content_base64), (c) => c.charCodeAt(0));
      const url = URL.createObjectURL(new Blob([bytes]));
      const a = document.createElement('a');
      a.href = url; a.download = n;
      document.body.append(a); a.click(); a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
      ptOut.innerHTML = `<span class="tag ok">saved</span> ${esc(n)} · ${r.bytes} B · md5 ${esc((r.md5 || '').slice(0, 8))}`;
      remember(n);
    } catch (e) {
      const gone = e instanceof ApiError && e.status === 404;
      ptOut.innerHTML = `<span class="tag ${gone ? '' : 'bad'}">${gone ? 'declined' : 'failed'}</span> `
        + `<span class="small dim">${esc(e.message)}</span>`;
    }
  };

  $id('#pt-file').onchange = async (ev) => {
    const f = ev.target.files[0];
    ev.target.value = '';
    if (!f) return;
    const n = f.name.endsWith('.db') ? f.name : `${f.name}.db`;
    if (!(await confirmGateway(
      `Restoring ${n} OVERWRITES every taught position in that table on the `
      + 'controller. This transfer path is unverified on real hardware; the '
      + 'readback verdict will be shown after the write.', {
        title: 'Restore point table?', confirmLabel: 'Restore', danger: true,
      }))) return;
    ptOut.innerHTML = '<span class="small dim">restoring…</span>';
    try {
      const buf = new Uint8Array(await f.arrayBuffer());
      let bin = '';
      for (let i = 0; i < buf.length; i += 0x8000) {
        bin += String.fromCharCode.apply(null, buf.subarray(i, i + 0x8000));
      }
      const r = await api.put(`/api/v1/points/tables/${encodeURIComponent(n)}`,
        { content_base64: btoa(bin), confirm: true }, { timeout: 60000 });
      ptOut.innerHTML = `<span class="tag ${r.readback === 'confirmed' ? 'ok' : 'warn'}">`
        + `readback: ${esc(r.readback || 'unknown')}</span>`;
      remember(n);
      log(`restored point table ${n} (readback ${r.readback})`, 'warn');
    } catch (e) {
      ptOut.innerHTML = `<span class="tag bad">restore failed</span> <span class="small dim">${esc(e.message)}</span>`;
    }
  };

  const switchTo = async (n, label) => {
    ptOut.innerHTML = '<span class="small dim">switching…</span>';
    try {
      const r = await api.post(
        `/api/v1/points/tables/${encodeURIComponent(n)}/switch`, {});
      ptOut.innerHTML = `<span class="tag ok">active: ${esc(String(r.active ?? 'none'))}</span>`;
      if (n !== '-') remember(n);
      log(label, 'ok');
    } catch (e) {
      ptOut.innerHTML = `<span class="tag bad">switch failed</span> <span class="small dim">${esc(e.message)}</span>`;
    }
  };
  $id('#pt-switch').onclick = () => { const n = tableName(); if (n) switchTo(n, `switched point table to ${n}`); };
  $id('#pt-off').onclick = () => switchTo('-', 'point table deactivated');

  // --- drag teach (experimental, unverified) ------------------------------
  const dtState = $id('#dt-state');
  const pollDrag = async () => {
    try {
      const r = await api.post('/api/v1/invoke/IsInDragTeach', { args: [] });
      const v = Array.isArray(r.result) ? r.result[r.result.length - 1] : r.result;
      dtState.innerHTML = `state: <b>${v ? 'IN drag teach' : 'normal'}</b>`;
    } catch (e) { dtState.textContent = `state unknown (${e.message})`; }
  };
  pollDrag();
  const dragSwitch = async (on) => {
    if (!(await confirmGateway(
      `${on ? 'Enter' : 'Exit'} drag-teach (hand-guide) mode. This wire `
      + 'command is NOT verified on this hardware. Keep clear of the arm; '
      + 'poll the state below rather than trusting the button.', {
        title: `${on ? 'Enter' : 'Exit'} drag teach?`,
        confirmLabel: on ? 'Enter' : 'Exit', danger: true,
      }))) return;
    try {
      await api.post('/api/v1/invoke/DragTeachSwitch',
        { args: [on ? 1 : 0], confirm: true });
      log(`drag teach ${on ? 'on' : 'off'} commanded`, 'warn');
    } catch (e) { toast(e.message, 'err'); log(`drag teach: ${e.message}`, 'err'); }
    setTimeout(pollDrag, 600);
  };
  $id('#dt-on').onclick = () => dragSwitch(true);
  $id('#dt-off').onclick = () => dragSwitch(false);

  let dragTimer = setInterval(() => {
    if (!root.closest('section')?.hidden) pollDrag();
  }, 5000);
  teach.refresh = () => { showFrames(); pollDrag(); };
  // eslint-disable-next-line no-unused-vars
  void dragTimer;
}

export const TEACH_PANELS = { teach };
